export const CHAT_SELECTED = 'CHAT_SELECTED';
export const CANCEL_CHAT_SELECTED = 'CANCEL_CHAT_SELECTED';

export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const CANCEL_GET_CHAT_MESSAGES = 'CANCEL_GET_CHAT_MESSAGES';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const CANCEL_ADD_MESSAGE = 'CANCEL_ADD_MESSAGE';

export const TYPING = 'TYPING';