export const CHAT_SELECTED = 'CHAT_SELECTED';
export const CANCEL_CHAT_SELECTED = 'CANCEL_CHAT_SELECTED';

export const FETCH_CHAT_MESSAGES = 'FETCH_CHAT_MESSAGES';
export const FETCH_CHAT_MESSAGES_SUCCESS = 'FETCH_CHAT_MESSAGES_SUCCESS';
export const CANCEL_FETCH_CHAT_MESSAGES = 'CANCEL_FETCH_CHAT_MESSAGES';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const CANCEL_ADD_MESSAGE = 'CANCEL_ADD_MESSAGE';

export const TYPING = 'TYPING';